### ISSUE TITLE
collected Data flickering issue

### ISSUE THREAD

**Issue by hskAlena** [Aladoro/domain-robust-visual-il#1]
Hello, I'm currently using your data collecting code, 'env', but it has some issues.

When I plot 'expert_ims.npy' into images, which has (100, 4, 48, 48, 3) shape,
it shows black or gray images inserted in the sequence 'regularly'. 
I guess it is not my computer problem since I can export images without black/gray screen with other gym simulators.

![image](https://user-images.githubusercontent.com/52067195/116846579-862f1f00-ac23-11eb-970f-f92f4d039a43.png)

Please let me know how to fix it.

**Comment by Aladoro** [comment]
Hello! Good job noticing this, I believe it should be a nasty problem stemming from Mujoco's offscreen rendering, which libraries is your installation of Mujoco using to do this?

Additionally, if you try commenting out 'GlfwContext(offscreen=True)' at environment creation, do you still get the same problem? (In 'envs.envs.py')

Let me know ^^

**Comment by hskAlena** [comment]
Hello! I'm sorry but I don't get what you mean by the libraries of Mujoco, but my mujoco_py version is 2.0.2.13 !
I have mjpro131, mjpro150, mujoco200 installed, so I guess mujoco version won't matter :)

I've tried commenting out 'GlfwContext(offscreen=True)' but then I get "(GLEW initalization error: Missing GL version)", which can be solved by undoing the commenting.
As far as I know, not getting error message with GlfwContext commented out can only be done by rendering in 'human' mode, which makes getting image matrices impossible.

Interestingly, I get this kind of 'black and gray screen error' only in 'Reacher', 'Hopper', 'Striker' environment. 
(In Hopper and Striker, the background image is still shown, but the agent hopper disappears/ get blurred / get darker.)
![image](https://user-images.githubusercontent.com/52067195/118228713-9e295d00-b4c5-11eb-9fba-3908084a6a22.png)

Also, I get more black images in 'expert_data' than in 'prior_data'.

I've tried changing frame_skip number N "mujoco_env.MujocoEnv.__init__(self, path_to_xml, N)" into higher/lower numbers, but it doesn't seem to solve the problem. 

Any ideas? Thanks a lot :)

**Comment by hskAlena** [comment]
I moved FrameBufferEnv class into sampler.py and solved this issue. 
Still confused about the source of the error(yeah maybe sth with Glfwoffscreen had trouble..) , but I'm not getting this error anymore after splitting FrameBufferEnv from gym environment. :)
Thanks!

**Comment by Aladoro** [comment]
Sorry for not getting back to you sooner, and thanks for sharing your solution!
I have not encountered such issues running the experiments from different machines, so I believe it was likely specific to your mujoco installation. If you can narrow down what was causing it, feel free to make a pull request ^^
